# Generated by Django 5.0.6 on 2024-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_file', models.FileField(upload_to='emails/')),
                ('template_file', models.FileField(upload_to='templates/')),
            ],
        ),
    ]
