# Generated by Django 5.1.1 on 2024-09-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0003_user_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
