# Generated by Django 5.0.6 on 2024-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendancesheet', '0002_employee_employeeattendance_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='supervisor_name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
